runtime: nodejs
env: flex

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: ascendant-bloom-259119:europe-west3:animal-care-opjspr